# Generated by Django 5.0.6 on 2026-06-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='transaction_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='ledger.transactionline'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_store_prodcat'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'name'], name='inventory_p_store_i_f8e704_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='uniq_store_sku'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['store', 'product', 'created_at'], name='inventory_s_store_i_d42eb4_idx'),
        ),
    ]
