# Generated by Django 5.0.6 on 2026-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/features/')),
                ('layout', models.CharField(choices=[('left', 'Image left'), ('right', 'Image right')], default='right', max_length=8)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('nav', 'Top nav'), ('footer', 'Footer')], db_index=True, default='nav', max_length=8)),
                ('section', models.CharField(blank=True, help_text='Footer column heading.', max_length=40)),
                ('label', models.CharField(max_length=60)),
                ('href', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('group', 'order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('windows', 'Windows')], max_length=10)),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cms/screens/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('chrome', models.CharField(choices=[('browser', 'Browser'), ('phone', 'Phone'), ('windows', 'Windows')], default='browser', max_length=10)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Mero Dokan', max_length=80)),
                ('hero_headline', models.CharField(default='Revenue-first analytics', max_length=160)),
                ('hero_highlight', models.CharField(default='Revenue-first', help_text='Substring of the headline to highlight.', max_length=80)),
                ('hero_subheadline', models.CharField(default='Turn receipts and bills into stock, sales and insight, fast.', max_length=300)),
                ('social_proof_count', models.CharField(default='15,285', max_length=20)),
                ('primary_cta_label', models.CharField(default='Get started', max_length=40)),
                ('primary_cta_href', models.CharField(default='/auth/register/', max_length=200)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
