# Generated by Django 5.0.6 on 2026-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Gemini API key. Stored in DB; never exposed to frontend.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(blank=True, default='', help_text='Override Gemini model name (leave blank to use env default).', max_length=80),
        ),
    ]
