# Generated by Django 5.0.6 on 2026-06-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extracteddocument',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='processing.extracteddocument'),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='uploads.uploadedfile'),
        ),
        migrations.AddIndex(
            model_name='extracteddocument',
            index=models.Index(fields=['uploaded_by', 'invoice_date'], name='processing__uploade_0e5590_idx'),
        ),
        migrations.AddIndex(
            model_name='extracteddocument',
            index=models.Index(fields=['vendor_name', 'invoice_date'], name='processing__vendor__91a5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['name'], name='processing__name_ab1da5_idx'),
        ),
    ]
